### ISSUE TITLE
Case-insensitive by default

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/fnd#3]

**Comment by sergeevabc** [comment]
Err… Sorry to bother you here.

```console
$ fd media
Irfanview -- media\ 
ShareX -- media\    
foobar2000 -- media\
```

Is there a native way to get the output sorted by alphabet, but case-insensitive?
```console
foobar2000 -- media\
Irfanview -- media\ 
ShareX -- media\
```

I expect it because both Windows Search and Everything sort like that by default.

**Comment by tmccombs** [comment]
In general, fd doesn't sort the output. If you want sorted output, you should probably use `sort` or similar.
